name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: 1.13
      - run: |
          go mod download
          go test -v -cover
